name: ✨Feature Request
description: Submit feature request
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Suggest an Idea
      description: explain your idea
    validations:
      required: true
